export const banlist = [
      "Ancient Den",
      "Great Furnace",
      "Tree of Tales",
      "Vault of Whispers",
      "Seat of the Synod",
      "Blazing Shoal",
      "Chrome Mox",
      "Cloudpost",
      "Creeping Chill",
      "Counterbalance",
      "Dark Depths",
      "Deathrite Shaman",
      "Dig Through Time",
      "Eye of Ugin",
      "Gitaxian Probe",
      "Golgari Grave-Troll",
      "Hypergenesis",
      "Krark-Clan Ironworks",
      "Mental Misstep",
      "Ponder",
      "Rite of Flame",
      "Second Sunrise",
      "Summer Bloom",
      "Skullclamp",
      "Treasure Cruise",
      "Umezawa's Jitte"
];

